<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đăng nhập</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/auth.css"></head>
<body><main class="auth-page"><section class="auth-shell compact-shell">
<aside class="auth-visual"><div class="brand"><div class="brand-mark">U</div><span>UTE Shopping</span></div><div class="visual-copy"><h1>Chào mừng<br>quay trở lại.</h1><p>Đăng nhập để quản lý tài khoản, sản phẩm và tiếp tục trải nghiệm mua sắm.</p><div class="feature-list"><div class="feature-item"><span class="feature-icon">✓</span> Đăng nhập nhanh và an toàn</div><div class="feature-item"><span class="feature-icon">✓</span> Hỗ trợ khôi phục mật khẩu qua Gmail OTP</div></div></div><div></div></aside>
<div class="auth-panel"><div class="auth-panel-inner"><div class="auth-head"><h2>Đăng nhập</h2><p>Nhập tài khoản và mật khẩu của bạn.</p></div>
<% if ("1".equals(request.getParameter("activated"))) { %><div class="alert alert-success">Kích hoạt tài khoản thành công. Bạn có thể đăng nhập ngay.</div><% } %>
<% if ("1".equals(request.getParameter("reset"))) { %><div class="alert alert-success">Đổi mật khẩu thành công. Hãy đăng nhập bằng mật khẩu mới.</div><% } %>
<% if (request.getAttribute("alert") != null) { %><div class="alert alert-error"><%= request.getAttribute("alert") %></div><% } %>
<form action="${pageContext.request.contextPath}/login" method="post"><div class="form-group"><label>Tài khoản</label><div class="input-wrap"><input type="text" name="username" placeholder="Nhập tài khoản" required autofocus><span class="input-icon">👤</span></div></div><div class="form-group"><label>Mật khẩu</label><div class="input-wrap"><input id="loginPassword" type="password" name="password" placeholder="Nhập mật khẩu" required><button class="toggle-password" type="button" data-toggle-password="loginPassword">👁</button></div></div><div class="form-row"><label class="checkbox"><input type="checkbox" name="remember"> Ghi nhớ đăng nhập</label><a class="inline-link" href="${pageContext.request.contextPath}/forgot-password">Quên mật khẩu?</a></div><button class="auth-btn" type="submit">Đăng nhập</button><div class="auth-footer">Chưa có tài khoản? <a href="${pageContext.request.contextPath}/register">Đăng ký miễn phí</a></div></form>
</div></div></section></main><script src="${pageContext.request.contextPath}/assets/js/auth.js"></script></body></html>
